# Generated by Django 5.1.4 on 2024-12-07 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('coverage_zones', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_services', models.CharField(blank=True, max_length=150, null=True)),
                ('operating_hours', models.IntegerField(blank=True, null=True)),
                ('service_rates', models.IntegerField(blank=True, null=True)),
                ('vehicle_types', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(default='a', max_length=50)),
                ('business_sector', models.CharField(choices=[('Logistics', 'Logistics'), ('Insurance', 'Insurance'), ('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing'), ('Trading', 'Trading')], default='a', max_length=50)),
                ('pix', models.ImageField(upload_to='merchant')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
