# Generated by Django 5.1.4 on 2024-12-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='phone',
            new_name='company_phone_number',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='pix',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='delivery_services',
        ),
        migrations.AddField(
            model_name='merchant',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_sector',
            field=models.CharField(choices=[('Logistics', 'Logistics'), ('Insurance', 'Insurance'), ('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing'), ('Trading', 'Trading')], max_length=50),
        ),
    ]
