# Generated by Django 5.1.4 on 2024-12-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_rename_email_merchant_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='vehicle_types',
        ),
        migrations.AddField(
            model_name='merchant',
            name='kyc_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Merchant_KYC_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_document', models.ImageField(upload_to='media/images')),
                ('registration_document', models.ImageField(upload_to='media/images')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant')),
            ],
        ),
    ]
