# Generated by Django 5.1.4 on 2024-12-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_remove_merchant_vehicle_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='company_phone_number',
            new_name='company_phone_number1',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='company_registration',
            new_name='company_phone_number2',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='kyc_is_verified',
            new_name='company_registration_kyc',
        ),
    ]
