# Generated by Django 5.1.4 on 2024-12-19 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_rename_company_phone_number_merchant_company_phone_number1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
