from django.urls import path
from django.contrib.auth import views as auth_views
from main import views
from .views import merchregistration, verify_email, find_nearest_seller, find_nearest_delivery_service, find_nearest_delivery_service

urlpatterns = [
    path('', views.home, name='home'),
    path('products', views.products, name='products'), 
    path('category/<str:id>/<slug:slug>', views.category, name='category'),
    path('featureitem/<str:id>/<slug:slug>', views.featureitem, name='featureitem'),
    path('detail/<str:id>/<slug:slug>', views.detail, name='detail'),
    path('featuredetail/<str:id>/<slug:slug>', views.featuredetail, name='featuredetail'),
    path('contact', views.contact, name='contact'),
    path('signout', views.signout, name='signout'),
    path('signin', views.signin, name='signin'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('profile_update', views.profile_update, name='profile_update'),
    path('password_update', views.password_update, name='password_update'),
    path('register/', merchregistration, name='merchregistration'),
    path('verify-email/<uidb64>/<token>/', verify_email, name='verify_email'),
    path('partnerregistration', views.partnerregistration, name='partnerregistration'),
    path('kyc_upload', views.kyc_upload, name='kyc_upload'),
    path('merchsignin', views.merchsignin, name='merchsignin'),
    path('merhprofile', views.merchprofile, name='merchprofile'),
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('cart', views.cart, name='cart'),
    path('delete', views.delete, name='delete'),
    path('update', views.update, name='update'),
    path('chekout', views.checkout, name='checkout'),
    path('pay', views.pay, name='pay'),
    path('callback', views.callback, name='callback'),
    path('search', views.search, name='search'),
    path('subscribes', views.subscribes, name='subscribes'),
    path('reset_password/', 
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"), 
         name="reset_password"),
    path('reset_password_sent/', 
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), 
         name="password_reset_confirm"),
    path('reset_password_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
         name="password_reset_complete"),
    path('nearest_locations_for_customer/<int:customer_id>/', views.find_nearest_seller, name='nearest_locations_for_customer'),
    path('nearest_locations_for_merchant/<int:merchant_id>/', views.find_nearest_delivery_service, name='nearest_locations_for_merchant'),
    path('find_nearest_delivery_service/<int:merchant_id>/', views.find_nearest_delivery_service, name='find_nearest_delivery_service'),
    path('merchant/dashboard/', views.merchant_dashboard, name='merchant_dashboard'),
]

