# Generated by Django 5.1.4 on 2024-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pix',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
