# Generated by Django 5.1.4 on 2024-12-19 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_pix_customer_customer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
