# Generated by Django 5.1.4 on 2024-12-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='security_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
