# Generated by Django 5.1.4 on 2024-12-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0002_rename_email_merchant_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category_slug', models.SlugField(max_length=20, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_img', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subcategory_slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_img', models.ImageField(upload_to='media/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categ_subcategory', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('condition', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('kilogram', models.FloatField()),
                ('availability', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo_price', models.IntegerField(blank=True, null=True)),
                ('telephone1', models.CharField(max_length=50)),
                ('telephone2', models.CharField(blank=True, max_length=50, null=True)),
                ('side_img', models.ImageField(upload_to='media/images')),
                ('front_img', models.ImageField(upload_to='media/images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_value', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_vat_exempt', models.BooleanField(default=False, help_text='Select if this product is VAT exempt (0%).')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=1)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcateg_products', to='product.subcategory')),
            ],
        ),
    ]
