# Generated by Django 5.1.4 on 2024-12-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('merchant', '0002_rename_email_merchant_company_email_and_more'),
        ('product', '0002_rename_seller_product_merchant_remove_product_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_img',
            new_name='subcategory_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='telephone1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='telephone2',
        ),
        migrations.AddField(
            model_name='product',
            name='closeup_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_merchant', to='merchant.merchant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='product_rating', to='product.rating'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='product_review', to='product.review'),
        ),
    ]
