# Generated by Django 5.0.4 on 2024-09-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureitem',
            name='sponsorname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='availability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_value',
            field=models.FloatField(),
        ),
    ]
