# Generated by Django 5.0.4 on 2024-05-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_featureproduct_type_delete_carts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
