# Generated by Django 5.0.4 on 2024-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_featureitem_sponsorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kilogram',
            field=models.FloatField(default='0.0'),
        ),
    ]
