# Generated by Django 5.0.4 on 2024-06-24 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_featureproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('company_address', models.CharField(max_length=150)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('coverage_zones', models.CharField(max_length=50)),
                ('company_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_services', models.CharField(max_length=150)),
                ('operating_hours', models.IntegerField(blank=True, null=True)),
                ('service_rates', models.IntegerField(blank=True, null=True)),
                ('vehicle_types', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(max_length=50)),
                ('pix', models.ImageField(upload_to='delieryservice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
