# Generated by Django 5.0.4 on 2024-06-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delivery_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_service',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='delivery_service',
            name='first_name',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
