# Generated by Django 5.0.4 on 2024-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_delivery_service_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_service',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
