# Generated by Django 5.0.4 on 2024-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_delivery_service_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_service',
            name='last_name',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
