# Generated by Django 5.0.4 on 2024-06-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delivery_service_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_service',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
