# Generated by Django 5.0.4 on 2024-06-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_delivery_service_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery_Service',
        ),
    ]
