# Generated by Django 5.0.4 on 2024-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_delivery_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='availability',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_sector',
            field=models.CharField(choices=[('Logistics', 'Logistics'), ('Insurance', 'Insurance'), ('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing'), ('Trading', 'Trading')], default='Logistics', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='coverage_zones',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='delivery_services',
            field=models.CharField(default='a', max_length=150),
        ),
        migrations.AddField(
            model_name='merchant',
            name='operating_hours',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='postcode',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='service_rates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='vehicle_types',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
