# Generated by Django 5.0.4 on 2024-10-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_payment_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice_number',
        ),
    ]
