# Generated by Django 5.0.4 on 2024-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merchant_availability_merchant_business_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='availability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_sector',
            field=models.CharField(choices=[('Logistics', 'Logistics'), ('Insurance', 'Insurance'), ('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing'), ('Trading', 'Trading')], max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='coverage_zones',
            field=models.CharField(blank=True, default='a', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='delivery_services',
            field=models.CharField(blank=True, default='a', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='operating_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='service_rates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='vehicle_types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
