# Generated by Django 5.0.4 on 2024-10-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_payment_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vat_exempt',
            field=models.BooleanField(default=False, help_text='Select if this product is VAT exempt (0%).'),
        ),
    ]
