# Generated by Django 5.0.4 on 2024-06-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_merchant_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='coverage_zones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='delivery_services',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
