# Generated by Django 5.0.4 on 2024-07-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_merchant_coverage_zones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address_type',
            field=models.CharField(choices=[('seller', 'Seller Address'), ('delivery', 'Delivery Service Address')], default='seller', max_length=8),
        ),
    ]
