# Generated by Django 5.0.4 on 2024-10-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_product_unpaid_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unpaid_count',
        ),
    ]
