# Generated by Django 5.0.4 on 2024-11-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
