# Generated by Django 5.0.4 on 2024-11-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='canceled',
        ),
    ]
