# Generated by Django 5.0.4 on 2024-11-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_product_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
