# Generated by Django 5.0.4 on 2024-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_cart_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
