# Generated by Django 5.0.4 on 2024-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
