# Generated by Django 5.0.4 on 2025-03-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
