# Generated by Django 5.0.4 on 2025-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='product',
            name='instructions',
            field=models.TextField(default='a'),
        ),
    ]
