# Generated by Django 5.1.4 on 2024-12-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitems_product'),
        ('product', '0004_rename_text_review_review_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart', 'product')},
        ),
    ]
