# Generated by Django 5.1.4 on 2024-12-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainauth', '0002_customuserverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
